<?php

/**
 * bootstrap/app.php
 *
 * Laravel 11 application bootstrap.
 * The full file is generated by `composer create-project laravel/laravel`.
 * The sections marked ADDED below are the only changes needed for Phase 1.
 *
 * Run to scaffold the real file:
 *   composer create-project laravel/laravel backend-laravel "^11.0"
 *
 * Then apply the ADDED lines from this file into the generated bootstrap/app.php.
 */

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        api: __DIR__ . '/../routes/api.php',   // ← ADDED: explicit API routes file
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware): void {
        $middleware->alias([
            'abilities' => \Laravel\Sanctum\Http\Middleware\CheckAbilities::class,
            'ability' => \Laravel\Sanctum\Http\Middleware\CheckForAnyAbility::class,
        ]);

        // ---------------------------------------------------------------
        // ADDED: Register AES-256-GCM encryption as a global API middleware
        // It runs on every /api/* route, before controllers are reached.
        // ---------------------------------------------------------------
        $middleware->api(prepend: [
            \App\Http\Middleware\EncryptApiPayload::class,
        ]);

        // ---------------------------------------------------------------
        // ADDED: Tell Sanctum which frontend domains can use session auth
        // ---------------------------------------------------------------
        // $middleware->statefulApi();

        // ---------------------------------------------------------------
        // ADDED: Trust the X-Forwarded-* headers when behind a reverse proxy
        // (needed when deploying behind Nginx / Apache)
        // ---------------------------------------------------------------
        $middleware->trustProxies(at: '*');
    })
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })
    ->create();
