'use client';

import { useMemo, useState } from 'react';
import jsPDF from 'jspdf';

export interface PendingCertificateRequest {
  id: string;
  studentName: string;
  studentNumber: string;
  courseDept: string;
  reason: string;
  requestedDateIso: string;
  proofFileName?: string;
  status: 'pending' | 'approved' | 'denied';
}

interface CertificateApprovalTableProps {
  initialRequests: PendingCertificateRequest[];
  approverName?: string;
  className?: string;
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function generateCertificatePdf(request: PendingCertificateRequest, approverName: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const width = doc.internal.pageSize.getWidth();

  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, width, 90, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('GC HealthLink Medical Certificate', 40, 40);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Issued on ${new Date().toLocaleString('en-US')}`, 40, 62);

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.text('This certifies that:', 40, 130);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(request.studentName, 40, 160);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Student Number: ${request.studentNumber}`, 40, 185);
  doc.text(`Program: ${request.courseDept}`, 40, 205);
  doc.text('has been evaluated by the campus clinic and is issued this certificate for:', 40, 235);

  doc.setFont('helvetica', 'bold');
  doc.text(request.reason, 40, 265);

  doc.setFont('helvetica', 'normal');
  doc.text(`Requested Date: ${formatDate(request.requestedDateIso)}`, 40, 295);
  doc.text(`Approved by: ${approverName}`, 40, 315);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('This document is generated by GC HealthLink for mock/testing workflows.', 40, 760);

  doc.save(`medical_certificate_${request.studentNumber}.pdf`);
}

export default function CertificateApprovalTable({
  initialRequests,
  approverName = 'Clinic Staff',
  className,
}: CertificateApprovalTableProps) {
  const [rows, setRows] = useState<PendingCertificateRequest[]>(initialRequests);
  const [selectedStatus, setSelectedStatus] = useState<'all' | PendingCertificateRequest['status']>('pending');
  const [query, setQuery] = useState('');

  const visibleRows = useMemo(() => {
    const q = query.trim().toLowerCase();

    return rows
      .filter((row) => (selectedStatus === 'all' ? true : row.status === selectedStatus))
      .filter((row) => {
        if (!q) return true;
        return (
          row.studentName.toLowerCase().includes(q)
          || row.studentNumber.toLowerCase().includes(q)
          || row.reason.toLowerCase().includes(q)
        );
      })
      .sort((a, b) => new Date(b.requestedDateIso).getTime() - new Date(a.requestedDateIso).getTime());
  }, [rows, query, selectedStatus]);

  function updateStatus(id: string, status: PendingCertificateRequest['status']) {
    setRows((current) => current.map((row) => (row.id === id ? { ...row, status } : row)));
  }

  function handleApprove(request: PendingCertificateRequest) {
    updateStatus(request.id, 'approved');
    generateCertificatePdf(request, approverName);
  }

  function handleDeny(request: PendingCertificateRequest) {
    updateStatus(request.id, 'denied');
  }

  return (
    <section className={`rounded-2xl border border-gray-100 bg-white p-5 shadow-sm ${className ?? ''}`.trim()}>
      <header className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-sm font-semibold text-gray-900">Medical Certificate Approval</h2>
          <p className="mt-1 text-xs text-gray-500">Review pending requests, approve/deny, and generate certificate PDF on approval.</p>
        </div>

        <div className="inline-flex rounded-xl border border-gray-200 bg-gray-50 p-1">
          {(['pending', 'approved', 'denied', 'all'] as const).map((status) => (
            <button
              key={status}
              type="button"
              onClick={() => setSelectedStatus(status)}
              className={`rounded-lg px-2.5 py-1 text-xs font-medium capitalize transition ${
                selectedStatus === status
                  ? 'bg-teal-600 text-white'
                  : 'text-gray-600 hover:bg-white hover:text-teal-700'
              }`}
            >
              {status}
            </button>
          ))}
        </div>
      </header>

      <div className="mb-4">
        <input
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Search request..."
          className="w-full rounded-xl border border-gray-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-300"
        />
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full text-sm">
          <thead>
            <tr className="border-b border-gray-100 text-left text-xs uppercase tracking-wide text-gray-500">
              <th className="px-3 py-2 font-semibold">Student</th>
              <th className="px-3 py-2 font-semibold">Reason</th>
              <th className="px-3 py-2 font-semibold">Requested</th>
              <th className="px-3 py-2 font-semibold">Proof</th>
              <th className="px-3 py-2 font-semibold">Status</th>
              <th className="px-3 py-2 font-semibold">Actions</th>
            </tr>
          </thead>
          <tbody>
            {visibleRows.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-3 py-10 text-center text-sm text-gray-400">No certificate requests found.</td>
              </tr>
            ) : (
              visibleRows.map((row) => (
                <tr key={row.id} className="border-b border-gray-50">
                  <td className="px-3 py-3">
                    <p className="font-semibold text-gray-800">{row.studentName}</p>
                    <p className="text-xs text-teal-600">{row.studentNumber} • {row.courseDept}</p>
                  </td>
                  <td className="px-3 py-3 text-gray-700">{row.reason}</td>
                  <td className="px-3 py-3 text-gray-600">{formatDate(row.requestedDateIso)}</td>
                  <td className="px-3 py-3 text-gray-600">{row.proofFileName || 'No attachment'}</td>
                  <td className="px-3 py-3">
                    <span
                      className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold ${
                        row.status === 'approved'
                          ? 'bg-green-100 text-green-700'
                          : row.status === 'denied'
                            ? 'bg-red-100 text-red-700'
                            : 'bg-amber-100 text-amber-700'
                      }`}
                    >
                      {row.status}
                    </span>
                  </td>
                  <td className="px-3 py-3">
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={() => handleApprove(row)}
                        disabled={row.status === 'approved'}
                        className="rounded-lg bg-teal-500 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-teal-600 disabled:opacity-50"
                      >
                        Approve
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDeny(row)}
                        disabled={row.status === 'denied'}
                        className="rounded-lg border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red-600 hover:bg-red-50 disabled:opacity-50"
                      >
                        Deny
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
