'use client';

import { useEffect, useMemo, useState } from 'react';
import jsPDF from 'jspdf';

export type CertificateStatus = 'pending' | 'pending_doctor' | 'doctor_approved' | 'denied';

export interface PendingCertificateRequest {
  id: string;
  studentName: string;
  studentNumber: string;
  courseDept: string;
  reason: string;
  requestedDateIso: string;
  proofFileName?: string;
  status: CertificateStatus;
  doctorName?: string;
}

interface CertificateApprovalTableProps {
  initialRequests: PendingCertificateRequest[];
  approverName?: string;
  className?: string;
}

const STORAGE_KEY = 'gchl_cert_requests';

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function generateCertificatePdf(request: PendingCertificateRequest, doctorName: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const width = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, width, 90, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('GC HealthLink Medical Certificate', 40, 40);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Issued on ${new Date().toLocaleString('en-US')}`, 40, 62);

  // Body
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.text('This certifies that:', 40, 130);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(request.studentName, 40, 160);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Student Number: ${request.studentNumber}`, 40, 185);
  doc.text(`Program: ${request.courseDept}`, 40, 205);
  doc.text('has been evaluated by the campus clinic and is issued this certificate for:', 40, 235);

  doc.setFont('helvetica', 'bold');
  doc.text(request.reason, 40, 265);

  doc.setFont('helvetica', 'normal');
  doc.text(`Requested Date: ${formatDate(request.requestedDateIso)}`, 40, 295);
  doc.text(`Approved by: ${doctorName}`, 40, 315);
  doc.text('Released by: Clinic Staff', 40, 335);

  // Signature line
  doc.setDrawColor(15, 118, 110);
  doc.line(40, 680, 240, 680);
  doc.setFontSize(10);
  doc.text(doctorName, 40, 695);
  doc.text('Campus Physician', 40, 710);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('This document is generated by GC HealthLink Clinic Management System.', 40, 760);

  doc.save(`medical_certificate_${request.studentNumber}.pdf`);
}

/** Load persisted requests from localStorage, falling back to initial data. */
function loadFromStorage(initial: PendingCertificateRequest[]): PendingCertificateRequest[] {
  if (typeof window === 'undefined') return initial;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return initial;
    const parsed: PendingCertificateRequest[] = JSON.parse(raw);
    // Merge: use stored status for existing ids, keep initial for new ones
    const storedMap = new Map(parsed.map((r) => [r.id, r]));
    return initial.map((r) => storedMap.get(r.id) ?? r);
  } catch {
    return initial;
  }
}

function saveToStorage(rows: PendingCertificateRequest[]) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(rows));
  } catch { /* ignore */ }
}

const STATUS_FILTER_OPTIONS = ['pending', 'pending_doctor', 'doctor_approved', 'denied', 'all'] as const;
type StatusFilter = (typeof STATUS_FILTER_OPTIONS)[number];

const STATUS_LABELS: Record<CertificateStatus, string> = {
  pending: 'Pending',
  pending_doctor: 'Awaiting Doctor',
  doctor_approved: 'Doctor Approved',
  denied: 'Denied',
};

const STATUS_COLORS: Record<CertificateStatus, string> = {
  pending: 'bg-amber-100 text-amber-700',
  pending_doctor: 'bg-blue-100 text-blue-700',
  doctor_approved: 'bg-emerald-100 text-emerald-700',
  denied: 'bg-red-100 text-red-700',
};

export default function CertificateApprovalTable({
  initialRequests,
  approverName = 'Campus Physician',
  className,
}: CertificateApprovalTableProps) {
  const [rows, setRows] = useState<PendingCertificateRequest[]>(() =>
    loadFromStorage(initialRequests)
  );
  const [selectedStatus, setSelectedStatus] = useState<StatusFilter>('pending');
  const [query, setQuery] = useState('');

  // Sync from localStorage whenever we come back (doctor may have approved)
  useEffect(() => {
    const synced = loadFromStorage(initialRequests);
    setRows(synced);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function updateRow(id: string, patch: Partial<PendingCertificateRequest>) {
    setRows((current) => {
      const updated = current.map((row) => (row.id === id ? { ...row, ...patch } : row));
      saveToStorage(updated);
      return updated;
    });
  }

  function handleRequestDoctorApproval(row: PendingCertificateRequest) {
    updateRow(row.id, { status: 'pending_doctor' });
  }

  function handleRelease(row: PendingCertificateRequest) {
    const doctor = row.doctorName || approverName;
    generateCertificatePdf(row, doctor);
    // Keep status as doctor_approved (already released); optionally mark released
  }

  function handleDeny(row: PendingCertificateRequest) {
    updateRow(row.id, { status: 'denied' });
  }

  const visibleRows = useMemo(() => {
    const q = query.trim().toLowerCase();
    return rows
      .filter((row) => (selectedStatus === 'all' ? true : row.status === selectedStatus))
      .filter((row) => {
        if (!q) return true;
        return (
          row.studentName.toLowerCase().includes(q) ||
          row.studentNumber.toLowerCase().includes(q) ||
          row.reason.toLowerCase().includes(q)
        );
      })
      .sort((a, b) => new Date(b.requestedDateIso).getTime() - new Date(a.requestedDateIso).getTime());
  }, [rows, query, selectedStatus]);

  const pendingCount = rows.filter((r) => r.status === 'pending').length;
  const awaitingCount = rows.filter((r) => r.status === 'pending_doctor').length;
  const readyCount = rows.filter((r) => r.status === 'doctor_approved').length;

  return (
    <section className={`rounded-2xl border border-gray-100 bg-white p-5 shadow-sm ${className ?? ''}`.trim()}>

      {/* Info Banner */}
      <div className="mb-4 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-xs text-blue-700 flex items-start gap-2">
        <svg className="w-4 h-4 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>
          <strong>Two-step workflow:</strong> Staff requests doctor approval → Doctor approves on their dashboard → Staff releases the certificate PDF.
        </span>
      </div>

      {/* Stats Row */}
      <div className="mb-4 grid grid-cols-3 gap-3">
        <div className="rounded-xl border border-amber-100 bg-amber-50 p-3 text-center">
          <p className="text-lg font-bold text-amber-600">{pendingCount}</p>
          <p className="text-xs text-amber-500 mt-0.5">Pending Requests</p>
        </div>
        <div className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-center">
          <p className="text-lg font-bold text-blue-600">{awaitingCount}</p>
          <p className="text-xs text-blue-500 mt-0.5">Awaiting Doctor</p>
        </div>
        <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-center">
          <p className="text-lg font-bold text-emerald-600">{readyCount}</p>
          <p className="text-xs text-emerald-500 mt-0.5">Ready to Release</p>
        </div>
      </div>

      <header className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-sm font-semibold text-gray-900">Medical Certificate Requests</h2>
          <p className="mt-1 text-xs text-gray-500">Request doctor approval, then release the certificate PDF.</p>
        </div>

        <div className="inline-flex rounded-xl border border-gray-200 bg-gray-50 p-1 flex-wrap gap-0.5">
          {STATUS_FILTER_OPTIONS.map((status) => (
            <button
              key={status}
              type="button"
              onClick={() => setSelectedStatus(status)}
              className={`rounded-lg px-2.5 py-1 text-xs font-medium capitalize transition ${
                selectedStatus === status
                  ? 'bg-teal-600 text-white'
                  : 'text-gray-600 hover:bg-white hover:text-teal-700'
              }`}
            >
              {status === 'pending_doctor' ? 'Awaiting' : status === 'doctor_approved' ? 'Approved' : status}
            </button>
          ))}
        </div>
      </header>

      <div className="mb-4">
        <input
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Search by student name, ID, or reason..."
          className="w-full rounded-xl border border-gray-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-300"
        />
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full text-sm">
          <thead>
            <tr className="border-b border-gray-100 text-left text-xs uppercase tracking-wide text-gray-500">
              <th className="px-3 py-2 font-semibold">Student</th>
              <th className="px-3 py-2 font-semibold">Reason</th>
              <th className="px-3 py-2 font-semibold">Requested</th>
              <th className="px-3 py-2 font-semibold">Proof</th>
              <th className="px-3 py-2 font-semibold">Status</th>
              <th className="px-3 py-2 font-semibold">Actions</th>
            </tr>
          </thead>
          <tbody>
            {visibleRows.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-3 py-10 text-center text-sm text-gray-400">
                  No certificate requests found.
                </td>
              </tr>
            ) : (
              visibleRows.map((row) => (
                <tr key={row.id} className="border-b border-gray-50 hover:bg-gray-50/60 transition-colors">
                  <td className="px-3 py-3">
                    <p className="font-semibold text-gray-800">{row.studentName}</p>
                    <p className="text-xs text-teal-600">{row.studentNumber} • {row.courseDept}</p>
                  </td>
                  <td className="px-3 py-3 text-gray-700">{row.reason}</td>
                  <td className="px-3 py-3 text-gray-600 whitespace-nowrap">{formatDate(row.requestedDateIso)}</td>
                  <td className="px-3 py-3 text-gray-600">{row.proofFileName || 'No attachment'}</td>
                  <td className="px-3 py-3">
                    <span className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold ${STATUS_COLORS[row.status]}`}>
                      {STATUS_LABELS[row.status]}
                    </span>
                    {row.status === 'doctor_approved' && row.doctorName && (
                      <p className="text-xs text-gray-400 mt-0.5">by {row.doctorName}</p>
                    )}
                  </td>
                  <td className="px-3 py-3">
                    <div className="flex gap-2 flex-wrap">

                      {/* Pending → ask doctor */}
                      {row.status === 'pending' && (
                        <button
                          type="button"
                          onClick={() => handleRequestDoctorApproval(row)}
                          className="rounded-lg bg-blue-500 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-blue-600"
                        >
                          Request Doctor Approval
                        </button>
                      )}

                      {/* Pending doctor → waiting indicator */}
                      {row.status === 'pending_doctor' && (
                        <span className="inline-flex items-center gap-1 rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1.5 text-xs font-semibold text-blue-600">
                          <svg className="w-3 h-3 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                              d="M12 4v1m0 14v1M4 12H3m18 0h-1m-2.636-6.364l-.707.707M6.343 17.657l-.707.707m12.728 0l-.707-.707M6.343 6.343l-.707-.707" />
                          </svg>
                          Awaiting Doctor
                        </span>
                      )}

                      {/* Doctor approved → release PDF */}
                      {row.status === 'doctor_approved' && (
                        <button
                          type="button"
                          onClick={() => handleRelease(row)}
                          className="rounded-lg bg-emerald-500 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-emerald-600"
                        >
                          Release Certificate
                        </button>
                      )}

                      {/* Deny — always available except when already denied */}
                      {row.status !== 'denied' && (
                        <button
                          type="button"
                          onClick={() => handleDeny(row)}
                          className="rounded-lg border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red-600 hover:bg-red-50"
                        >
                          Deny
                        </button>
                      )}

                      {row.status === 'denied' && (
                        <span className="text-xs font-semibold text-red-400">Denied</span>
                      )}
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
